FROM ghcr.io/open-webui/open-webui:main
ENV ENABLE_OLLAMA_API="False"
ENV OPENAI_API_BASE_URL="https://hitanshuac-hybrid-ai-router-vision.hf.space/v1"
ENV OPENAI_API_KEY="sk-antigravity"
ENV WEBUI_SECRET_KEY="antigravity_secret_key_2026"
